constants:
  - corpus
variables:
  nts: ["classic"]
  guide: ["strict"]
  hmarkov: ["0"]
  vmarkov: ["1"]
  lr: ["1e-2", "1e-3", "1e-4"]
  decay: ["1e-1", "1e-2", "1e-3"]
commands:
  - "disutapa extract --headrules [headrules] --nts [nts] --guide [guide] --hmarkov [hmarkov] --vmarkov [vmarkov] [corpus] ./corpora/negra-[nts]-[guide]-[hmarkov]-[vmarkov]"
  - "disutapa train --epochs 10 --embedding Supervised --lr [lr] --weight-decay [decay] --parameter-search ./corpora/negra-[nts]-[guide]-[hmarkov]-[vmarkov] /tmp/train-lr-[lr]-[decay]"
